escolha='s'
while escolha=='s':
    saldo=float(input('Digite o valor de seu saldo: '))
    r1=str(input('Nome da receita: ')).capitalize()
    receita1=float(input('Digite o valor de sua receita: '))
    r2=str(input('Nome da receita: ')).capitalize()
    receita2=float(input('Digite o valor de sua receita: '))
    r3=str(input('Nome da receita: ')).capitalize()
    receita3=float(input('Digite o valor de sua receita: '))
    d1=str(input('Nome da despesa: ')).capitalize()
    despesa1=float(input('Digite o valor de sua despesa: '))
    d2=str(input('Nome da despesa: ')).capitalize()
    despesa2=float(input('Digite o valor de sua despesa: '))
    d3=str(input('Nome da despesa: ')).capitalize()
    despesa3=float(input('Digite o valor de sua despesa: '))
    receitas=(receita1+receita2+receita3)
    despesas=(despesa1+despesa2+despesa3)
    saldo_final=((saldo+receitas)-despesas)
    print(f'Despesas:{despesas}\n {d1,d2,d3} \nReceitas: {receitas}\n {r1,r2,r3} \nSeu saldo atual é de {saldo_final} ')
    escolha=str(input('Deseja repetir o processo?\nS/N  ')).lower()